(part "CME0303S3C"
    (packageRef "CME0303S3C")
    (interface
        (port "1" (symbPinId 1) (portName "-VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "+VIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "-VOUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "+VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "CME0303S3C")
    (property "Mouser_Part_Number" "580-CME0303S3C")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Power-Solutions/CME0303S3C?qs=XKx0tEJeiQ3UXTrSkJqzTw%3D%3D")
    (property "Arrow_Part_Number" "CME0303S3C")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/cme0303s3c/murata-power-solutions?region=nac")
    (property "Description" "Murata Power Solutions CME 0.75W Isolated DC-DC Converter Through Hole, Vin 2.97  3.63 V dc, Vout 3.3V dc")
    (property "Datasheet_Link" "https://www.murata.com/products/productdata/8807029342238/kdc-cme.pdf?1614569448000")
    (property "symbolName1" "CME0303S3C")
)
