(part "SRR1260-150M"
    (packageRef "SRR1260-150M")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "SRR1260-150M")
    (property "Mouser_Part_Number" "652-SRR1260-150M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/SRR1260-150M?qs=y9m3SKnhpLPF5BoYDkDwgQ%3D%3D")
    (property "Arrow_Part_Number" "SRR1260-150M")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/srr1260-150m/bourns.html?utm_currency=USD&region=nac")
    (property "Description" "Power inductor SMD shielded 15uH 5A Bourns SRR1260 Series Shielded Wire-wound SMD Inductor with a Ferrite Core, 15 uH +/-20% 5A Idc Q:25")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/SFDatasheet-7/sf-000140468.pdf")
    (property "symbolName1" "SRR1260-150M")
)
