(part "AMC1200SDUBR"
    (packageRef "SOP254P1040X485-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VINP") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VINN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VOUTN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VOUTP") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "AMC1200SDUBR")
    (property "Mouser_Part_Number" "595-AMC1200SDUBR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/AMC1200SDUBR?qs=Nxfnlnd%252BiAcMKGpoVxsKlg%3D%3D")
    (property "Arrow_Part_Number" "AMC1200SDUBR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/amc1200sdubr/texas-instruments.html?utm_currency=USD&region=nac")
    (property "Description" "Isolation Amplifiers 4kV peak Iso Amp")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/AMC1200")
    (property "symbolName1" "AMC1200SDUBR")
)
